### ISSUE TITLE
How to dismiss the petal if I touch outside the petal ?

### ISSUE THREAD

**Issue by avocet** [KieranLafferty/KLExpandingSelect#1]
How to dismiss the petal if I touch outside the petal ?

**Comment by 0xjmp** [comment]
There is a function named "collapseItems" in the KLExpandingSelect.m that you should find useful to close the petals.

**Comment by KieranLafferty** [comment]
Thanks jsksma2 for answering this one

**Comment by 0xjmp** [comment]
No problem. While I have your attention, all of your Gits are awesome, and I would love to collaborate with you on a future project sometime!

**Comment by KieranLafferty** [comment]
That would be great! Be sure to keep me in the loop on what you are up to

**Comment by 0xjmp** [comment]
Well, I'm finishing up a new app for the iPhone this week or the next.
Perhaps you could give me some insight and tips to make my code more
efficient? I actually have the KLExpandingSelect Git in it currently with a
small tweak to make the items expand on the view's load.

On Monday, December 10, 2012, Kieran Lafferty wrote:

> That would be great! Be sure to keep me in the loop on what you are up to
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/KieranLafferty/KLExpandingSelect/issues/1#issuecomment-11225772.

## 

Jake Peterson
951.333.2642
Jsksma2@gmail.com
