### ISSUE TITLE
No dismiss when touching outside

### ISSUE THREAD

**Issue by eaceto** [KieranLafferty/KLExpandingSelect#2]
I think it will be a great idea if when opening the context menu, you add a transparent layer in all the screen and the flower over it. So when touching outside of the flower (on the transparent layer) the flower can be closed. Like a "touch outside to dismiss".

**Comment by KieranLafferty** [comment]
Hello eaceto, thank you for the suggestion but for the sake of developer freedom I wanted to make this a design choice of the developer implementing the control as it is not guaranteed that everyone would like this functionality
